In [4]:
import numpy as np

In [15]:
myarr = np.array([4,5,3,53])

In [13]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarr.shape

(3, 3)

In [11]:
listarr.size

9

In [12]:
np.array({32,34,23,2,23})

array({32, 34, 2, 23}, dtype=object)

In [17]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
b = np.linspace(1,50,5)
b

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [1]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar.sum(axis=0)

array([12, 15, 18])

In [8]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [16]:
myarr.argsort()

array([2, 0, 1, 3])